### ISSUE TITLE
Error on installing

### ISSUE THREAD

**Issue by JounouchiAng** [XSmeagolX/BOINC-Userstats#14]
Hi sir,
First thanks for your hard work regarding BOINC Userstats.
Can you please share the installation guide in English?
I tried to install but getting white page whenever I open index.php or cronjob.php, not sure what is the issue.
Meanwhile any installation guide for this old version? (https://www.seti-germany.de/wcg/39_en_Personal%20WCG-Stats.html)

Thanks for help.

**Comment by XSmeagolX** [comment]
First thing you Clan do:

Go to settings/settings.php and set

ini_set ('display_errors', 'Off');

to

ini_set ('display_errors', 'On');

and open the index.php on your Webbrowser.
Maybe there are good hints to find the problems regarding to your installation.

English translation of the webpage is in my todo list. :)

**Comment by XSmeagolX** [comment]
The old wcg stats will be included in this project in future time.
The current team history and project overview with Badges is actual included.

**Comment by JounouchiAng** [comment]
Hi, thanks for answer.

Just successfully make the old v1.01 version run this afternoon.

For the new v7.30, I think is my PHP version issue because it is not in PHP v7, is it workable in PHP 5?

**Comment by XSmeagolX** [comment]
Php5 should work, if db connection and queries with mysqli is supported

**Comment by JounouchiAng** [comment]
I will try.

Is it the program need to be install at the root folder (www.xxx.com)? Can be inside in subfolder (www.xxx.com/WCG)?

**Comment by XSmeagolX** [comment]
They should work relative, so you can store them inside a subfolder.

**Comment by JounouchiAng** [comment]
Ok, did what you told me by using display_errors to On.

Manually run cron job give me blank page.

For index, getting this:
Warning: include(./errordocs/db_initial_err.php.): failed to open stream: No such file or directory in /storage/ssd3/016/1944016/public_html/boinc_userstats/db/boinc_db.php on line 61

Warning: include(): Failed opening './errordocs/db_initial_err.php.' for inclusion (include_path='.:/usr/share/pear:/usr/share/php') in /storage/ssd3/016/1944016/public_html/boinc_userstats/db/boinc_db.php on line 61

**Comment by XSmeagolX** [comment]
The Output of the cronjob.php will always end in a blank Site. :)

Did you store the folder /errordocs/ and its content on the webspace?
Did you edited the boinc_db.php file with your credentials?
Is PHP5 running on your Webserver?
Did you edit the settings/settings.php file to your needs?

**Comment by XSmeagolX** [comment]
and one more question:
Did you edit line 6 of the cronjob.php file?

include "/path/to/db_connect.php";

**Comment by JounouchiAng** [comment]
1. Yes, I upload the whole folder that download from release through FTP to web hosting.
2. Yes, edit with my own DB info.
3. Yes, PHP 7.1
4. Yes, in database, for the two table boinc_user and boinc_grundwerte.
5. I just edit the settings to turn on the error that you mentioned previously.
6. I change the path to ./db/boinc_db.php same errors.

**Comment by XSmeagolX** [comment]
Do you get a 404 when directly open the url http://your-site.url/boinc_userstats/errordocs/db_initial_err.php?

Can you edit the boinc_db.php on line 61 to absolute path to the db_initial_err.php and tell me, if this is working?

**Comment by JounouchiAng** [comment]
1. I get blank page when open using URL.
2. I edit line 61 without the dot behind and it works well. 

But getting infinite loop when open index.php.

> Warning: mysqli_num_rows() expects parameter 1 to be mysqli_result, boolean given in /storage/ssd3/016/1944016/public_html/boinc_userstats/db/boinc_db.php on line 34
> 
> Warning: mysqli_num_rows() expects parameter 1 to be mysqli_result, boolean given in /storage/ssd3/016/1944016/public_html/boinc_userstats/db/boinc_db.php on line 34
> 

And when I login using PHPMyAdmin to check settings.. getting this error:

> SQL query: Edit Edit
> SET CHARACTER SET 'utf8';
> MySQL said: Documentation
> #1226 - User 'id1944016_boinc_userstats' has exceeded the 'max_queries_per_hour' resource (current value: 15000)

**Comment by XSmeagolX** [comment]
I made an english translation of the installation guide:

https://userstats.timo-schneider.de/install_en.html

**Comment by JounouchiAng** [comment]
Hi, sorry, what you mean by contact? I am using 000webhost to test as it is the one I found that have PHP 7.0, you may google.

**Comment by XSmeagolX** [comment]
cont**r**act, not contact. :D
I mean, you do not have a webserver, that you have personally installed by yourself. You are using a webhoster as a provider for your webspace.
So you are in dependance concerning the service of your provider, in case of database management and external file download.
My stats are using "@file_get_contents" to get the data of the external project server. This needs to be allowed by your webhost-provider. (not sure, this could be an option like allow_furl_open)
As I can see on 000webhost, fopen() seems to be allowed.

But this in fact do not concern to the errormessage you received.

What happens, if you paste "SELECT * FROM boinc_user LIMIT 1" into phpmyadmin?

**Comment by JounouchiAng** [comment]
I know there is a typo so I edited just now, haha.

Got 1 row result returned which I manually insert during installation.

**Comment by XSmeagolX** [comment]
typo?

**Comment by XSmeagolX** [comment]
For me it seems to be a problem with the right management in your database.
Is your $dbuser granted with all rights on your boinc database?
Are you "working" on the right database?

Your error will only appear, when the table doesn't exists or your $dbuser is not allowed to read the table.

**Comment by XSmeagolX** [comment]
mostly, web provider service includes ONE database, so you are not allowed to create more databases.
In this case, just create the tables by using the boinc.sql file into your database.
Be aware, that you type in the correct database name, user and password in boinc_db.php

**Comment by JounouchiAng** [comment]
Typing error. what I want to type is Contract instead of Contact.

I tried with wrong db info, getting this error.

`Warning: mysqli_connect(): (HY000/1045): ProxySQL Error: Access denied for user 'id1944016_boinc_userstats'@'2a02:4780:bad:f00d::a' (using password: YES) in /storage/ssd3/016/1944016/public_html/boinc_userstats/db/boinc_db.php on line 6

Warning: mysqli_connect(): (HY000/1045): ProxySQL Error: Access denied for user 'id1944016_boinc_userstats'@'2a02:4780:bad:f00d::a' (using password: YES) in /storage/ssd3/016/1944016/public_html/boinc_userstats/db/boinc_db.php on line 6`

I think the DB info in PHP file is correct, just it fires too many times (maybe unlimited loop so phpMyAdmin saying exceed the query limit).

**Comment by XSmeagolX** [comment]
It seems, that this is an issue of your provider, not in my code. :D
Are you or your provider using ProxySQL?
Are you using the NiuX panel or the old panel?

Some links i found on error with ProxySQL:
https://www.000webhost.com/forum/t/proxysql-error-issue/40355
https://github.com/sysown/proxysql/issues/709
https://github.com/sysown/proxysql/issues/959

Not sure, if this will help you.

**Comment by JounouchiAng** [comment]
Even though maybe the ProxySQL issue, I will try to switch to another DB and see.

But myself I'm not PHP background, it will took some times for me to figure out whats wrong with it.

Will let you know if I successfully install the version 7.3.

**Comment by XSmeagolX** [comment]
I'm sure, you mean Version 4.3.0, not 7.3 or 7.30... :D
Thanks for your interest in my stats and have a look on what's going on by browsing to 
https://timo-schneider.de/boinc_dev
where the next step to Version 5 (branch "Entwicklung zu Version 5") can be previewed and when it gets to beta, it can be previewed at
https://timo-schneider.de/boinc_test

this will take a while. :D

I let this issue opened until you got the stats running, so feel free to let me know.
It will be closes after 2 month, with no more response. :D

**Comment by JounouchiAng** [comment]
Hi there.

Just find out some issues.

Why in boinc_db.php, there is a checking "SELECT * FROM boinc_werte LIMIT 1"?

I thought initially there is only 2 tables with 1 record each which is boinc_grundwerte and boinc_user?

I commented the checking and able to run cronjob now (saw data updates)

**Comment by XSmeagolX** [comment]
as you can see in the boinc.sql-file, which should be imported in your database using for example phpmyadmin, there will be created FOUR tables.
boinc_user
boinc_grundwerte
boinc_werte
boinc_werte_day

the first two tables needs to be filled with your personal and project data
the other two tables will be filled with data from the cronjob/cronjob.php.

The "check" in boinc_db.php, with "SELECT * FROM boinc_werte LIMIT 1" is for the following reason:
He will check, if there are already values in the boinc_werte table. If not, your cronjob did not fetch any data and store this in the table. You will get a special "answer" on the webpage, that you need to wait until your first data import from the projects.

**Comment by XSmeagolX** [comment]
and you can work on more than just one boinc project.
Seti@home, World Community Grid, Primegrid, Einstein@home or what ever...
Every project, you are participating in needs to be in the boinc_grundwerte table.

**Comment by JounouchiAng** [comment]
Sorry, I am not PHP background, correct me if I'm wrong.

Your cronjob first include boinc_db.php first, which mean it will run the checking right?

Inside boinc_db.php, until the checking of boinc_werte,
```
	$result = mysqli_query($db_conn, "SELECT * FROM boinc_werte LIMIT 1");
	$rowCountResult = mysqli_num_rows($result);
	if ($rowCountResult < 1) {
		$connErrorTitle = "Datenbankfehler";
		$connErrorDescription = "Es wurden noch keine Daten abgerufen.</br>
		Bitte warte bis der erste erfolgreiche Datenabruf durchgeführt wurde.";
		include "./errordocs/db_initial_err.php";
		exit();
	}
```

It looks like it will go in and show error instead of running the cron job isn't?

**Comment by XSmeagolX** [comment]
Yes... you were right.

Just delete that check from boinc_db.php.
I need to reconstruct my error management for the cases of a clean install.
be aware, that the tables "boinc_werte" and "boinc_werte_day" are created prior executing the cronjob.php then!

Thanks for your help!

**Comment by XSmeagolX** [comment]
I released Version 4.3.2, where the errorhandling on fresh installation is disabled, so that the data from the projects will be fetched!

**Comment by JounouchiAng** [comment]
Hi, another issue from index.php

Notice: Undefined variable: table_retired in /storage/ssd3/016/1944016/public_html/boinc_userstats/index.php on line 539

Warning: Invalid argument supplied for foreach() in /storage/ssd3/016/1944016/public_html/boinc_userstats/index.php on line 539

**Comment by sgshka** [comment]
Hi, 
you can try to insert on line bevor 539

$table_retired = is_array($table_retired) or is_object($table_retired) ? $table_retired : [] ;

**Comment by JounouchiAng** [comment]
Looks like the same

Notice: Undefined variable: table_retired in /storage/ssd3/016/1944016/public_html/boinc_userstats/index.php on line 539

Warning: Invalid argument supplied for foreach() in /storage/ssd3/016/1944016/public_html/boinc_userstats/index.php on line 540

**Comment by sgshka** [comment]
before row 119  > while ($row = mysqli_fetch_assoc($query_getAllProjects)) {

insert:
$table_retired = array();

**Comment by XSmeagolX** [comment]
Thanks @sgshka for helping in this topic!

Download the latest index.php on branch master.
I added some checks on active and completed/retired projects.

Please tell me, if this is working for your case, so I could publish another release. :D

**Comment by JounouchiAng** [comment]
No more errors, but I will monitor the result and see if it is works well.

**Comment by XSmeagolX** [comment]
Thanks for using my stats.
Your issue helps me improving my stats.

Good to know, that they are now working.

**Comment by JounouchiAng** [comment]
Fatal error: Maximum execution time of 30 seconds exceeded in /storage/ssd3/016/1944016/public_html/boinc_userstats/project.php on line 64

Any idea? is it because of database performance issue?

**Comment by XSmeagolX** [comment]
Your Webserver is restricted to run scripts not longer than 30 sconds.
Normally the project.php took not longer than 1 second to get the data from database.
Specially, WCG could take more time, because he script fetches data live from the webpage of WCG.
But this also took mostly not longer than 2 or 3 seconds.

**Comment by JounouchiAng** [comment]
Not issue for today, no idea why. But getting different error.

Notice: Undefined variable: project_username in /storage/ssd3/016/1944016/public_html/boinc_userstats/lang/en.txt.php on line 4

Notice: Undefined variable: project_teamname in /storage/ssd3/016/1944016/public_html/boinc_userstats/lang/en.txt.php on line 4

**Comment by XSmeagolX** [comment]
But your username and teamname is shown in the stats?

Did you download and install the latest release 4.3.3?

**Comment by XSmeagolX** [comment]
And do not forget to set the display error to "Off" in settings/settings.php for security reasons, when the stats are running.
