### ISSUE TITLE
New sites don't work right away

### ISSUE THREAD

**Issue by tiker** [XSmeagolX/BOINC-Userstats#21]
I'm playing around with this project and am considering integrating something that I've been working on with it.

First issue I found deploying this as a new site is that the main page shows the headers and footer sections but no charts.  It took a couple of days before the site started working.

The problem is here:
https://github.com/XSmeagolX/BOINC-Userstats/blob/Version-5/web/index.php#L240

If someone creates a new site and adds a single project that their BOINC client is not actively working on, the site won't work.  This line prevents the site from working until a BOINC client submits completed work, gets credit for it and is then picked up by the cronjob updating the hourly stats.

This will make it a bit more difficult for someone who wants to see the site working fairly quickly after setting it up.

**Comment by XSmeagolX** [comment]
Hello tiker,

thanks for playing around with my project!
Yes, this could confusing, but without any data, there is (of course) nothing to show in the charts.
I will think about changing the error management for those cases and show a message, when no data is available for the charts.

Some question (just to be sure to understand the problem):
If you add a project where you are not actively working on, 
 1. this project is not shown in the table of the "project"-tab (or better: you will not see a project-table in the "project"-tab)?
 2. you do not get the error-page with the message: "Es noch keine Daten für eine Gesamtberechnung erstellt."
 3. You only see the header and footer with white space in between?

**Comment by tiker** [comment]
For example:
- Add a new project that has already completed (ABC@Home for example).
- It will have the total credits value set manually in the database.
- It will never receive an update through the cron job which means it will not add a line to the "boinc_werte" table and there will not be an entry with the project_shortname of "gesamt" in the table either.

Manually adding a project with total credit value should still show the page properly with the 1 project listed and the credits manually entered.  Not having an hourly update entry should not prevent the page from loading.

The main page looked like this:
http://www.funkymonkey.org/project.php?projectid=wcg  (temporary URL for now)
(This example is caused by a different problem which I'm working on figuring out but the page appearance was the same.)

**Comment by tiker** [comment]
I'll have to setup another instance of the site to test this.  The current site saw new credits for a project and added a row with"gesamt" to the "boinc_werte" table so issue is resolved for me.  I'll setup another instance to test this weekend.

**Comment by tiker** [comment]
This might be the same sort of issue with the http://www.funkymonkey.org/project.php?projectid=wcg issue I have now.  New projects added with a "begin_credits" and "total_credits" value > 0 and no entries in the hourly or daily tables are giving the same screen as you can see here.

I'll try apply this fix to project.php and see if that works.

**Comment by XSmeagolX** [comment]
a hint, on how the import is working and the reason for this issue:
To keep the database "small", the cronjob will only add a value to the database, when there is a difference to the prior hour (by project and by total).
This is the reason, why no data will be added, when you only have projects in the database, you are currently not working on and no actual credits get granted.

This is different to the Total-Chart. Everyday on your defined midnight (timezone settings in settings.php and cronjob.php), the credits of all ACTIVE projects (project_status = 1) and total will be added to the boinc_werte_day-Table, no matter if additional credits have been granted or not

**Comment by XSmeagolX** [comment]
and "gesamt" means "total". This row stored your combined total credits of the projects in your database.

**Comment by XSmeagolX** [comment]
on project.php you have to remove

 || mysqli_num_rows($query_getProjectOutputPerHour) === 0 

on lines 113 (and if you like on line 128)
when you have added the no-data-module in header.php

**Comment by XSmeagolX** [comment]
I made a new commit a6ac51d for a first approach to solve this issue.

**Comment by tiker** [comment]
I've updated my site with your changes.  The second issue appears to be resolved.  Haven't tested the first issue but I'd assume it'll be fixed as well.  Thanks.

I may merge one of my personal projects with this code to add some new features to it.  If I do and if you're interested, I'll create some pull requests here for it.  (Might require some database changes though.)

**Comment by XSmeagolX** [comment]
I'm not profession in coding (and also using github.. :D)
Let's see what happens, but do not feel angry, when I do not know, what your "contribution" will change in this project or how to migrate into my project. :D

**Comment by XSmeagolX** [comment]
Issue solved.
